const bookings = [['09:00', 'John Kamau', 'Haircut'], ['10:00', 'Peter Otieno', 'Haircut + Beard'], ['11:30', 'James Mwangi', 'Beard trim']];
const dueCustomers = [{ name: 'John Kamau', service: 'Haircut + Beard', due: 'Due today', initials: 'JK' }, { name: 'Mary Wanjiku', service: 'Knotless braids', due: 'Due today', initials: 'MW' }, { name: 'Peter Otieno', service: 'Haircut', due: 'Due soon', initials: 'PO' }];

export default function Home() {
  return <main className="app-shell">
    <aside className="sidebar"><a className="brand" href="#top"><span>R</span> RUDI</a><p className="business-switch">Brian&apos;s Barbershop <b>⌄</b></p><nav aria-label="Primary navigation"><a className="active" href="#top">⌂ &nbsp; Home</a><a href="#chat">◌ &nbsp; Chat <em>3</em></a><a href="#bookings">□ &nbsp; Bookings</a><a href="#customers">♙ &nbsp; Customers</a></nav><div className="sidebar-bottom"><a href="#settings">⚙ &nbsp; Settings</a><p>RUDI keeps your customers coming back.</p></div></aside>
    <section className="content" id="top"><header className="topbar"><div className="mobile-brand">RUDI</div><button className="icon-button" aria-label="Notifications">♢</button><button className="avatar" aria-label="Account menu">B</button></header>
      <div className="page-intro"><div><p className="eyebrow">Friday, 29 August</p><h1>Good morning, Brian <span>👋</span></h1><p className="subtle">Here&apos;s what&apos;s happening at your barbershop today.</p></div><button className="primary">+ New booking</button></div>
      <section className="metrics"><article><div className="metric-icon orange">▣</div><p>Appointments today</p><strong>8</strong><small>3 still to come</small></article><article><div className="metric-icon pink">↗</div><p>Customers due</p><strong>12</strong><small className="accent">Send them a reminder</small></article><article><div className="metric-icon blue">◌</div><p>Unread chats</p><strong>3</strong><small>Reply when you&apos;re ready</small></article></section>
      <section className="reminder-card" id="customers"><div><p className="eyebrow">Customer return</p><h2>12 customers are due today</h2><p>Bring them back with a simple, personal reminder.</p></div><div className="reminder-actions"><button className="light-button">Preview message</button><button className="dark-button">Send reminders →</button></div></section>
      <div className="dashboard-grid"><section className="panel" id="bookings"><div className="panel-heading"><div><h2>Today&apos;s bookings</h2><p>Friday, 29 August</p></div><a href="#bookings">View calendar →</a></div><div className="booking-list">{bookings.map(([time, name, service]) => <div className="booking" key={time}><time>{time}</time><span className="customer-dot">{name.charAt(0)}</span><div><strong>{name}</strong><p>{service}</p></div><button aria-label={`More options for ${name}`}>•••</button></div>)}</div></section>
      <section className="panel" id="chat"><div className="panel-heading"><div><h2>Recent chats</h2><p>Keep conversations moving</p></div><a href="#chat">Open chat →</a></div><div className="chat-list"><div><span className="customer-dot coral">J</span><p><strong>John Kamau</strong><br/><small>How much is a haircut?</small></p><time>2m</time></div><div><span className="customer-dot purple">M</span><p><strong>Mary Wanjiku</strong><br/><small>Tomorrow at 10 works for me.</small></p><time>28m</time></div><div><span className="customer-dot gold">P</span><p><strong>Peter Otieno</strong><br/><small>Thanks, see you then!</small></p><time>1h</time></div></div></section></div>
      <section className="panel due-panel"><div className="panel-heading"><div><h2>Customers to remind</h2><p>Based on their usual visit schedule</p></div><a href="#customers">View all customers →</a></div><div className="due-list">{dueCustomers.map((customer) => <div key={customer.name}><span className="customer-dot green">{customer.initials}</span><p><strong>{customer.name}</strong><small>{customer.service}</small></p><span className={customer.due === 'Due today' ? 'status due' : 'status'}>{customer.due}</span><button className="row-action">Remind</button></div>)}</div></section>
      <section className="setup-card"><div className="setup-number">01</div><div><h2>Start with your customers</h2><p>Import a CSV or Excel file, or add a customer in seconds. We&apos;ll never access contacts without your permission.</p></div><div className="setup-actions"><button className="light-button">+ Add customer</button><button className="dark-button">Import customers</button></div></section>
    </section></main>;
}
