import Fastify from 'fastify'; import cookie from '@fastify/cookie'; import cors from '@fastify/cors'; import rateLimit from '@fastify/rate-limit'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import { z } from 'zod'; import { db, query } from './db.js';
const app=Fastify({logger:true}),port=Number(process.env.PORT??3001),secret=process.env.SESSION_SECRET;if(!secret&&process.env.NODE_ENV==='production')throw Error('SESSION_SECRET required');
await app.register(cookie);await app.register(cors,{origin:(o,cb)=>cb(null,!o||o===process.env.WEB_ORIGIN),credentials:true});await app.register(rateLimit,{max:100,timeWindow:'1 minute'});
const normalPhone=v=>{const x=v.replace(/[\s-]/g,''),n=x.startsWith('+254')?x:x.startsWith('254')?`+${x}`:x.startsWith('0')?`+254${x.slice(1)}`:null;if(!n||!/^\+254(7|1)\d{8}$/.test(n))throw Error('Invalid Kenyan phone');return n};const slug=v=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const sign=(u,b)=>jwt.sign({sub:u,business:b},secret??'dev-secret',{expiresIn:'7d'});const opts={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/'};
async function tenant(req,reply){try{const t=req.cookies.rudi_session||req.headers.authorization?.replace('Bearer ','');req.user=jwt.verify(t,secret??'dev-secret');const r=await query('SELECT 1 FROM business_members WHERE business_id=$1 AND user_id=$2',[req.user.business,req.user.sub]);if(!r.rowCount)throw Error()}catch{return reply.code(401).send({error:'Authentication required'})}}
app.get('/health',async()=>({status:'ok',service:'rudi-api'}));
app.post('/v1/auth/register',{config:{rateLimit:{max:10,timeWindow:'1 hour'}}},async(req,reply)=>{const b=z.object({name:z.string().min(2),email:z.string().email(),phone:z.string(),password:z.string().min(10),businessName:z.string().min(2),businessType:z.enum(['barbershop','salon'])}).parse(req.body),c=await db.connect();try{await c.query('BEGIN');const u=await c.query('INSERT INTO users(name,email,phone,password_hash) VALUES($1,$2,$3,$4) RETURNING id',[b.name,b.email.toLowerCase(),normalPhone(b.phone),await bcrypt.hash(b.password,12)]);let s=slug(b.businessName),i=1;while((await c.query('SELECT 1 FROM businesses WHERE slug=$1',[s])).rowCount)s=`${slug(b.businessName)}-${++i}`;const x=await c.query('INSERT INTO businesses(owner_id,name,slug,type) VALUES($1,$2,$3,$4) RETURNING id,slug',[u.rows[0].id,b.businessName,s,b.businessType]);await c.query('INSERT INTO business_members(business_id,user_id,role) VALUES($1,$2,$3)',[x.rows[0].id,u.rows[0].id,'owner']);await c.query('INSERT INTO subscriptions(business_id) VALUES($1)',[x.rows[0].id]);await c.query('COMMIT');reply.setCookie('rudi_session',sign(u.rows[0].id,x.rows[0].id),opts);return {business:x.rows[0]}}catch(e){await c.query('ROLLBACK');if(e.code==='23505')return reply.code(409).send({error:'Email exists'});throw e}finally{c.release()}});
app.post('/v1/auth/login',{config:{rateLimit:{max:10,timeWindow:'15 minutes'}}},async(req,reply)=>{const b=z.object({email:z.string().email(),password:z.string()}).parse(req.body),u=await query('SELECT id,password_hash FROM users WHERE email=$1',[b.email.toLowerCase()]);if(!u.rowCount||!await bcrypt.compare(b.password,u.rows[0].password_hash))return reply.code(401).send({error:'Invalid credentials'});const m=await query('SELECT business_id FROM business_members WHERE user_id=$1 LIMIT 1',[u.rows[0].id]);reply.setCookie('rudi_session',sign(u.rows[0].id,m.rows[0].business_id),opts);return {ok:true}});
app.post('/v1/auth/logout',async(_q,r)=>{r.clearCookie('rudi_session',{path:'/'});return {ok:true}});
app.get('/v1/dashboard',{preHandler:tenant},async req=>{const id=req.user.business,[b,c,a]=await Promise.all([query('SELECT name,slug FROM businesses WHERE id=$1',[id]),query("SELECT count(*) total,count(*) FILTER(WHERE last_visit_at IS NOT NULL AND frequency_days IS NOT NULL AND last_visit_at+(frequency_days||' days')::interval<=now()) due FROM customers WHERE business_id=$1",[id]),query("SELECT count(*) FROM appointments WHERE business_id=$1 AND starts_at::date=current_date AND status IN ('booked','confirmed')",[id])]);return {business:b.rows[0],customers:+c.rows[0].total,due:+c.rows[0].due,appointmentsToday:+a.rows[0].count}});
app.get('/v1/customers',{preHandler:tenant},async req=>({customers:(await query('SELECT id,name,phone,last_visit_at,frequency_days,source FROM customers WHERE business_id=$1 ORDER BY created_at DESC LIMIT 200',[req.user.business])).rows}));
app.post('/v1/customers',{preHandler:tenant},async(req,reply)=>{const b=z.object({name:z.string().min(2),phone:z.string(),frequencyDays:z.number().int().positive().max(365).optional(),lastVisitAt:z.string().datetime().optional()}).parse(req.body);try{const r=await query('INSERT INTO customers(business_id,name,phone,frequency_days,last_visit_at,source) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,phone',[req.user.business,b.name,normalPhone(b.phone),b.frequencyDays??null,b.lastVisitAt??null,'MANUAL']);return reply.code(201).send(r.rows[0])}catch(e){if(e.code==='23505')return reply.code(409).send({error:'Customer already exists'});throw e}});
app.setErrorHandler((e,_q,r)=>{app.log.error(e);r.code(e.name==='ZodError'?400:500).send({error:e.name==='ZodError'?'Invalid request':'Server error'})});app.listen({port,host:'0.0.0.0'}).catch(e=>{app.log.error(e);process.exit(1)});
