import Fastify from 'fastify'; import cookie from '@fastify/cookie'; import cors from '@fastify/cors'; import rateLimit from '@fastify/rate-limit'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import { z } from 'zod'; import { db, query } from './db.js';
const app=Fastify({logger:true}),port=Number(process.env.PORT??3001),secret=process.env.SESSION_SECRET;if(!secret&&process.env.NODE_ENV==='production')throw Error('SESSION_SECRET required');
const allowedOrigin=(origin)=>{if(!origin||origin===process.env.WEB_ORIGIN)return true;try{return /^rudi(?:-[a-z0-9-]+)?-sagide-dels-projects\.vercel\.app$/i.test(new URL(origin).hostname)}catch{return false}};
await app.register(cookie);await app.register(cors,{origin:(o,cb)=>cb(null,allowedOrigin(o)),credentials:true});await app.register(rateLimit,{max:100,timeWindow:'1 minute'});
const normalPhone=v=>{const x=v.replace(/[\s-]/g,''),n=x.startsWith('+254')?x:x.startsWith('254')?`+${x}`:x.startsWith('0')?`+254${x.slice(1)}`:null;if(!n||!/^\+254(7|1)\d{8}$/.test(n))throw Error('Invalid Kenyan phone');return n};const slug=v=>v.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const sign=(u,b)=>jwt.sign({sub:u,business:b},secret??'dev-secret',{expiresIn:'7d'});const opts={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:process.env.NODE_ENV==='production'?'none':'lax',path:'/'};
async function tenant(req,reply){try{const t=req.cookies.rudi_session||req.headers.authorization?.replace('Bearer ','');req.user=jwt.verify(t,secret??'dev-secret');const r=await query('SELECT 1 FROM business_members WHERE business_id=$1 AND user_id=$2',[req.user.business,req.user.sub]);if(!r.rowCount)throw Error()}catch{return reply.code(401).send({error:'Authentication required'})}}
app.get('/health',async()=>({status:'ok',service:'rudi-api'}));
app.post('/v1/auth/register',{config:{rateLimit:{max:10,timeWindow:'1 hour'}}},async(req,reply)=>{const b=z.object({name:z.string().min(2),email:z.string().email(),phone:z.string(),password:z.string().min(10),businessName:z.string().min(2),businessType:z.enum(['barbershop','salon'])}).parse(req.body),c=await db.connect();try{await c.query('BEGIN');const u=await c.query('INSERT INTO users(name,email,phone,password_hash) VALUES($1,$2,$3,$4) RETURNING id',[b.name,b.email.toLowerCase(),normalPhone(b.phone),await bcrypt.hash(b.password,12)]);let s=slug(b.businessName),i=1;while((await c.query('SELECT 1 FROM businesses WHERE slug=$1',[s])).rowCount)s=`${slug(b.businessName)}-${++i}`;const x=await c.query('INSERT INTO businesses(owner_id,name,slug,type) VALUES($1,$2,$3,$4) RETURNING id,slug',[u.rows[0].id,b.businessName,s,b.businessType]);await c.query('INSERT INTO business_members(business_id,user_id,role) VALUES($1,$2,$3)',[x.rows[0].id,u.rows[0].id,'owner']);await c.query('INSERT INTO subscriptions(business_id) VALUES($1)',[x.rows[0].id]);await c.query('COMMIT');reply.setCookie('rudi_session',sign(u.rows[0].id,x.rows[0].id),opts);return {business:x.rows[0]}}catch(e){await c.query('ROLLBACK');if(e.code==='23505')return reply.code(409).send({error:'Email exists'});throw e}finally{c.release()}});
app.post('/v1/auth/login',{config:{rateLimit:{max:10,timeWindow:'15 minutes'}}},async(req,reply)=>{const b=z.object({email:z.string().email(),password:z.string()}).parse(req.body),u=await query('SELECT id,password_hash FROM users WHERE email=$1',[b.email.toLowerCase()]);if(!u.rowCount||!await bcrypt.compare(b.password,u.rows[0].password_hash))return reply.code(401).send({error:'Invalid credentials'});const m=await query('SELECT business_id FROM business_members WHERE user_id=$1 LIMIT 1',[u.rows[0].id]);reply.setCookie('rudi_session',sign(u.rows[0].id,m.rows[0].business_id),opts);return {ok:true}});
app.post('/v1/auth/logout',async(_q,r)=>{r.clearCookie('rudi_session',{path:'/'});return {ok:true}});
app.get('/v1/dashboard',{preHandler:tenant},async req=>{const id=req.user.business,[b,c,a]=await Promise.all([query('SELECT name,slug FROM businesses WHERE id=$1',[id]),query("SELECT count(*) total,count(*) FILTER(WHERE last_visit_at IS NOT NULL AND frequency_days IS NOT NULL AND last_visit_at+(frequency_days||' days')::interval<=now()) due FROM customers WHERE business_id=$1",[id]),query("SELECT count(*) FROM appointments WHERE business_id=$1 AND starts_at::date=current_date AND status IN ('booked','confirmed')",[id])]);return {business:b.rows[0],customers:+c.rows[0].total,due:+c.rows[0].due,appointmentsToday:+a.rows[0].count}});
app.get('/v1/customers',{preHandler:tenant},async req=>({customers:(await query("SELECT id,name,phone,last_visit_at,frequency_days,source,whatsapp_allowed,sms_allowed,CASE WHEN last_visit_at IS NULL OR frequency_days IS NULL THEN 'ACTIVE' WHEN last_visit_at+(frequency_days||' days')::interval < now()-interval '7 days' THEN 'OVERDUE' WHEN last_visit_at+(frequency_days||' days')::interval <=now() THEN 'DUE' WHEN last_visit_at+(frequency_days||' days')::interval <=now()+interval '2 days' THEN 'DUE SOON' ELSE 'ACTIVE' END status FROM customers WHERE business_id=$1 ORDER BY created_at DESC LIMIT 200",[req.user.business])).rows}));
app.post('/v1/customers',{preHandler:tenant},async(req,reply)=>{const b=z.object({name:z.string().min(2),phone:z.string(),frequencyDays:z.number().int().positive().max(365).optional(),lastVisitAt:z.string().datetime().optional()}).parse(req.body);try{const r=await query('INSERT INTO customers(business_id,name,phone,frequency_days,last_visit_at,source) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,phone',[req.user.business,b.name,normalPhone(b.phone),b.frequencyDays??null,b.lastVisitAt??null,'MANUAL']);return reply.code(201).send(r.rows[0])}catch(e){if(e.code==='23505')return reply.code(409).send({error:'Customer already exists'});throw e}});
app.post('/v1/reminders',{preHandler:tenant},async(req,reply)=>{const b=z.object({customerIds:z.array(z.string().uuid()).min(1).max(200)}).parse(req.body);const result=await query("INSERT INTO automation_events(business_id,customer_id,event_type,due_date) SELECT c.business_id,c.id,'return_reminder',current_date FROM customers c WHERE c.business_id=$1 AND c.id=ANY($2::uuid[]) AND c.last_visit_at IS NOT NULL AND c.frequency_days IS NOT NULL AND c.last_visit_at+(c.frequency_days||' days')::interval<=now() AND (c.whatsapp_allowed OR c.sms_allowed) AND NOT c.opted_out ON CONFLICT(business_id,customer_id,event_type,due_date) DO NOTHING RETURNING customer_id",[req.user.business,b.customerIds]);return reply.send({queued:result.rowCount,skipped:b.customerIds.length-result.rowCount,message:'Reminders are queued once an approved WhatsApp or SMS provider is connected.'})});
app.get('/v1/services',{preHandler:tenant},async req=>({services:(await query('SELECT id,name,price_kes,duration_minutes FROM services WHERE business_id=$1 AND active=true ORDER BY name',[req.user.business])).rows}));
app.post('/v1/services',{preHandler:tenant},async(req,reply)=>{const b=z.object({name:z.string().min(2),priceKes:z.number().int().nonnegative().optional(),durationMinutes:z.number().int().positive().max(600).optional()}).parse(req.body);const r=await query('INSERT INTO services(business_id,name,price_kes,duration_minutes) VALUES($1,$2,$3,$4) RETURNING id,name,price_kes,duration_minutes',[req.user.business,b.name,b.priceKes??null,b.durationMinutes??null]);return reply.code(201).send(r.rows[0])});
app.get('/v1/bookings',{preHandler:tenant},async req=>({bookings:(await query("SELECT a.id,a.starts_at,a.ends_at,a.status,c.name customer,s.name service FROM appointments a JOIN customers c ON c.id=a.customer_id LEFT JOIN services s ON s.id=a.service_id WHERE a.business_id=$1 AND a.starts_at>=current_date ORDER BY a.starts_at LIMIT 100",[req.user.business])).rows}));
app.post('/v1/bookings',{preHandler:tenant},async(req,reply)=>{const b=z.object({customerId:z.string().uuid(),serviceId:z.string().uuid().optional(),startsAt:z.string().datetime(),endsAt:z.string().datetime(),staffName:z.string().max(80).optional()}).parse(req.body);try{const r=await query('INSERT INTO appointments(business_id,customer_id,service_id,staff_name,starts_at,ends_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,starts_at,status',[req.user.business,b.customerId,b.serviceId??null,b.staffName??null,b.startsAt,b.endsAt]);return reply.code(201).send(r.rows[0])}catch(e){if(e.code==='23505')return reply.code(409).send({error:'That staff member already has a booking at this time'});throw e}});
app.setErrorHandler((e,_q,r)=>{app.log.error(e);r.code(e.name==='ZodError'?400:500).send({error:e.name==='ZodError'?'Invalid request':'Server error'})});app.listen({port,host:'0.0.0.0'}).catch(e=>{app.log.error(e);process.exit(1)});
